name: Publish Python 🐍 distributions 📦 to PyPI
on:
  push:
  # schedule:
  #   - cron: '0 4 */1 * *'
jobs:
  build:
    name: Publish Python 🐍 distributions 📦 to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: 0
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install twine
      run: >-
        python -m
        pip install
        twine
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python setup.py sdist
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@main
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
        # repository_url: https://pypi.org/legacy/

      
